"""
Proposition 8: when does the affine collapse survive for non-abelian groups?

For a representation ``rho`` of a finite group ``G`` on ``R^D`` and ``H <= G``,

    V_H = { W : W rho(h) = rho(h) W  for all h in H },
    Pi_H(W) = (1/|H|) sum_{h in H} rho(h)^{-1} W rho(h),

and for ``R`` uniform on the unit sphere of ``V_G^perp``, dimension counting gives

    E_R delta_H^2 = eps^2 (p_1 - p_H) / (p_1 - p_G),      p_1 = D^2.

The collapse of Theorem 5 survives exactly when ``p_H`` is affine in ``1/|H|``
along the chain of subgroups considered.

Two corrections to the paper, both checked numerically here
-----------------------------------------------------------
1.  The paper writes ``p_H = sum_lambda m_lambda^2 dim(lambda)^2``.  The commutant
    of ``+_lambda m_lambda lambda`` has dimension ``sum_lambda m_lambda^2``; there
    is no ``dim(lambda)^2`` factor.  :func:`paper_parameter_count` evaluates the paper's
    expression exactly (as the rank of ``span(A . A')``) and
    :func:`commutant_dim_numeric` gives the true dimension by independent
    eigen-count, so both formulas can be compared.  They disagree whenever an occurring irrep has ``dim(lambda) > 1``.

2.  Proposition 8 says the collapse "can fail" when ``H`` has a higher-dimensional
    irrep.  In the **regular** representation this never happens.  ``C_d`` acting
    on ``R^d`` by shifts *is* its regular representation, so that is the setting
    the paper generalises, and there every non-identity element has zero trace:

        p_H = (1/|H|) sum_{h in H} tr(rho(h))^2 = |G|^2 / |H|

    for every subgroup of every finite group.  Hence
    ``gamma_H = |G|(1 - 1/|H|)/(|G| - 1)``, identical to the cyclic formula, and
    the collapse holds for ``S_3``, ``D_4``, ``S_4`` alike.  Where it fails is for
    *non-regular* representations: the natural permutation representation of
    ``S_4`` on ``R^4`` is shipped as a worked counterexample, and there interior
    subgroups genuinely win over a range of ``(eps, n)``.

Corrected statement: *the affine collapse survives iff ``p_H`` is affine in
``1/|H|``; this holds automatically in the regular representation of any finite
group, abelian or not, and can fail for other representations.*
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from itertools import combinations

import numpy as np

__all__ = [
    "Permutation",
    "generate_group",
    "subgroups",
    "regular_representation",
    "natural_representation",
    "commutant_dim_trace",
    "commutant_dim_numeric",
    "commutant_basis",
    "algebra_dim",
    "structure_string",
    "paper_parameter_count",
    "audit_group",
    "interior_optimum_scan",
    "GROUPS",
]

Permutation = tuple[int, ...]


# ------------------------------------------------------------------- groups


def compose(a: Permutation, b: Permutation) -> Permutation:
    return tuple(a[b[i]] for i in range(len(a)))


def inverse(a: Permutation) -> Permutation:
    out = [0] * len(a)
    for i, ai in enumerate(a):
        out[ai] = i
    return tuple(out)


def generate_group(gens: list[Permutation]) -> list[Permutation]:
    """Closure of ``gens`` under composition."""
    e = tuple(range(len(gens[0])))
    seen, frontier = {e}, [e]
    while frontier:
        nxt = []
        for x in frontier:
            for g in gens:
                y = compose(g, x)
                if y not in seen:
                    seen.add(y)
                    nxt.append(y)
        frontier = nxt
    return sorted(seen)


def subgroups(G: list[Permutation], max_gens: int = 2) -> list[list[Permutation]]:
    """All subgroups generated by at most ``max_gens`` elements, de-duplicated."""
    e = tuple(range(len(G[0])))
    found: dict[frozenset, list[Permutation]] = {frozenset([e]): [e]}
    for r in range(1, max_gens + 1):
        for combo in combinations(G, r):
            H = generate_group(list(combo))
            found[frozenset(H)] = H
    return sorted(found.values(), key=lambda H: (len(H), sorted(H)))


# ----------------------------------------------------------- representations


def _perm_matrix(p: Permutation) -> np.ndarray:
    n = len(p)
    M = np.zeros((n, n))
    M[np.arange(n), list(p)] = 1.0
    return M


def natural_representation(G: list[Permutation]) -> dict[Permutation, np.ndarray]:
    """Permutation matrices acting on the underlying ``n`` points."""
    return {g: _perm_matrix(g) for g in G}


def regular_representation(G: list[Permutation]) -> dict[Permutation, np.ndarray]:
    """Left regular representation on ``R^{|G|}``."""
    index = {g: i for i, g in enumerate(G)}
    rep = {}
    for g in G:
        M = np.zeros((len(G), len(G)))
        for h in G:
            M[index[compose(g, h)], index[h]] = 1.0
        rep[g] = M
    return rep


# --------------------------------------------------------- commutant dimension


def commutant_dim_trace(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> float:
    """``dim V_H = (1/|H|) sum_h tr(rho(h)) tr(rho(h)^{-1})``."""
    return float(sum(np.trace(rep[h]) * np.trace(rep[inverse(h)]) for h in H) / len(H))


def _averaging_operator(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> np.ndarray:
    """Matrix of ``W -> (1/|H|) sum_h rho(h)^T W rho(h)`` acting on row-major ``vec(W)``."""
    D = next(iter(rep.values())).shape[0]
    P = np.zeros((D * D, D * D))
    for h in H:
        A = rep[h]
        P += np.kron(A.T, A.T)       # vec(A^T W A) = (A^T (x) A^T) vec(W)
    return P / len(H)


def commutant_basis(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> np.ndarray:
    """Orthonormal basis of ``V_H``, shape ``(p_H, D, D)``."""
    D = next(iter(rep.values())).shape[0]
    P = _averaging_operator(H, rep)
    w, V = np.linalg.eigh((P + P.T) / 2)
    return V[:, w > 0.5].T.reshape(-1, D, D)


def commutant_dim_numeric(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> int:
    """``dim V_H`` by eigenvalue count (independent of the trace formula)."""
    P = _averaging_operator(H, rep)
    return int(np.sum(np.linalg.eigvalsh((P + P.T) / 2) > 0.5))


def algebra_dim(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> int:
    """
    ``dim span{rho(h) : h in H} = sum_lambda dim(lambda)^2``.

    (The double commutant theorem: the span of the image of the group algebra is
    ``+_lambda M_{dim lambda}``.)
    """
    M = np.stack([rep[h].ravel() for h in H])
    return int(np.linalg.matrix_rank(M, tol=1e-8))


def paper_parameter_count(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> int:
    """
    The paper's ``p_H = sum_lambda m_lambda^2 dim(lambda)^2``, computed without
    needing a character table.

    Writing ``A = span rho(H) = +_lambda M_{dim lambda}`` and ``A' = V_H =
    +_lambda M_{m_lambda}`` (the commutant), the span of products ``A . A'`` is
    ``+_lambda M_{dim lambda} (x) M_{m_lambda}``, whose dimension is exactly
    ``sum_lambda m_lambda^2 dim(lambda)^2``.  So the paper's quantity is the rank
    of the span of ``{rho(h) B : h in H, B in basis(V_H)}``.

    Both this and :func:`commutant_dim_trace` are evaluated in the same real
    matrix space the paper works in (Frobenius inner product on ``R^{D x D}``),
    so the comparison between them is like for like.  They coincide iff every
    occurring irrep is one-dimensional; otherwise the paper's expression
    overcounts, and it is ``commutant_dim_trace`` (equivalently
    :func:`commutant_dim_numeric`) that is the true parameter count.
    """
    basis = commutant_basis(H, rep)
    prods = np.stack([(rep[h] @ B).ravel() for h in H for B in basis])
    return int(np.linalg.matrix_rank(prods, tol=1e-8))


def structure_string(H: list[Permutation], rep: dict[Permutation, np.ndarray]) -> str:
    """Compact structure summary ``p_H | dim A | sum m^2 dim^2`` for the audit table."""
    return f"pH={commutant_dim_trace(H, rep):g};algA={algebra_dim(H, rep)};paper={paper_parameter_count(H, rep)}"


# ------------------------------------------------------------------- audit


@dataclass
class SubgroupRecord:
    order: int
    index: int
    p_H_trace: float
    p_H_numeric: int
    p_H_paper_formula: float
    decomposition: str
    gamma_H: float
    gamma_regular_prediction: float


def audit_group(name: str, gens: list[Permutation], rep_kind: str = "regular",
                verify_numeric: bool = True, max_numeric_D: int = 12,
                max_gens: int = 2) -> dict:
    """Compute ``p_H``, ``gamma_H`` for every subgroup; test affineness of ``gamma_H`` in ``1/|H|``."""
    G = generate_group(gens)
    rep = regular_representation(G) if rep_kind == "regular" else natural_representation(G)
    D = next(iter(rep.values())).shape[0]
    do_numeric = verify_numeric and D <= max_numeric_D

    subs = subgroups(G, max_gens=max_gens)
    p1, pG = float(D * D), commutant_dim_trace(G, rep)

    rows = []
    for H in subs:
        pH = commutant_dim_trace(H, rep)
        pH_num = commutant_dim_numeric(H, rep) if do_numeric else -1
        if do_numeric:
            paper_p = float(paper_parameter_count(H, rep))
            decomp_s = structure_string(H, rep)
        else:
            paper_p, decomp_s = float("nan"), ""
        gamma = (p1 - pH) / (p1 - pG) if p1 > pG else 0.0
        rows.append(SubgroupRecord(
            order=len(H), index=len(G) // len(H), p_H_trace=pH, p_H_numeric=pH_num,
            p_H_paper_formula=paper_p, decomposition=decomp_s, gamma_H=gamma,
            gamma_regular_prediction=D * (1.0 - 1.0 / len(H)) / (D - 1.0),
        ))

    u = np.array([1.0 / r.order for r in rows])
    g = np.array([r.gamma_H for r in rows])
    A = np.vstack([np.ones_like(u), u]).T
    coef, *_ = np.linalg.lstsq(A, g, rcond=None)
    resid = float(np.max(np.abs(A @ coef - g)))

    return {
        "name": name,
        "rep": rep_kind,
        "group_order": len(G),
        "D": D,
        "p1": p1,
        "pG": pG,
        "abelian": all(compose(a, b) == compose(b, a) for a in G for b in G),
        "rows": [asdict(r) for r in rows],
        "affine_max_residual": resid,
        "affine": bool(resid < 1e-9),
        "regular_formula_holds": bool(all(abs(r.p_H_trace - D * D / r.order) < 1e-9 for r in rows)),
        "paper_formula_matches": bool(
            do_numeric and all(abs(r.p_H_paper_formula - r.p_H_trace) < 1e-6 for r in rows)
        ),
        "numeric_verified": bool(do_numeric),
    }


def interior_optimum_scan(audit: dict, sigma: float = 0.5, eps_grid=None, n_grid=None) -> dict:
    """Scan ``(eps, n)``; count cells whose risk minimiser is an interior subgroup."""
    eps_grid = np.geomspace(0.05, 0.8, 9) if eps_grid is None else np.asarray(eps_grid)
    n_grid = np.geomspace(10, 1e5, 40) if n_grid is None else np.asarray(n_grid)
    rows = audit["rows"]
    orders = np.array([r["order"] for r in rows], dtype=float)
    pH = np.array([r["p_H_trace"] for r in rows], dtype=float)
    gamma = np.array([r["gamma_H"] for r in rows], dtype=float)

    interior, total, examples = 0, 0, []
    for eps in eps_grid:
        for n in n_grid:
            risk = eps**2 * gamma + sigma**2 * pH / n
            j = int(np.argmin(risk))
            total += 1
            if orders[j] not in (1.0, float(audit["group_order"])):
                interior += 1
                if len(examples) < 6:
                    examples.append({"eps": round(float(eps), 4), "n": round(float(n)),
                                     "order": int(orders[j])})
    return {"interior_cells": interior, "total_cells": total, "examples": examples}


#: Groups used in the Proposition 8 audit.
GROUPS: dict[str, list[Permutation]] = {
    "C4": [(1, 2, 3, 0)],
    "C6": [(1, 2, 3, 4, 5, 0)],
    "V4": [(1, 0, 3, 2), (2, 3, 0, 1)],
    "S3": [(1, 2, 0), (1, 0, 2)],
    "D4": [(1, 2, 3, 0), (3, 2, 1, 0)],
    "S4": [(1, 2, 3, 0), (1, 0, 2, 3)],
}
